apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
  - n8n-namespace.yaml
  - n8n-configmap.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-pvc.yaml
  - n8n-ingress.yaml

secretGenerator:
  - name: postgres-secret
    envs:
      - secrets/postgres.env
  - name: n8n-secret
    envs:
      - secrets/n8n.env

generatorOptions:
  disableNameSuffixHash: true
