apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  N8N_BASIC_AUTH_ACTIVE: {your_value_here}
  N8N_BASIC_AUTH_USER: {your_value_here}
  N8N_BASIC_AUTH_PASSWORD: {your_value_here}
  N8N_BASIC_AUTH_HASH: {your_value_here}
  N8N_ENCRYPTION_KEY: {your_value_here}
  N8N_HOST: {your_value_here}
  N8N_PORT: {your_value_here}
  N8N_PROTOCOL: {your_value_here}
  N8N_EDITOR_BASE_URL: {your_value_here}
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: {your_value_here}
