apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
data:
  POSTGRES_USER: {your_value_here}            
  POSTGRES_PASSWORD: {your_value_here}
  POSTGRES_DB: {your_value_here}                     
  POSTGRES_NON_ROOT_USER: {your_value_here}       
  POSTGRES_NON_ROOT_PASSWORD: {your_value_here}